language: node_js
node_js: node
cache:
  npm: true
jobs:
  include:
  - name: Build and Push
    script:
    - npm run build
    deploy:
      local_dir: ".vuepress/dist/"
      provider: pages
      skip_cleanup: true
      name: Travis Build Bot
      keep_history: true
      on:
        branch: master
      target_branch: gh-pages
      token:
        secure: huaXIb+EhuAbwdZZuEGjJ7UqP/o7/kf9gf3YGfao4cxeTr29oNFaSDwvQVh2YbOW5wLcberSyNxad+iP6u6U5ZHYMDR15DravIDd32ZrSWc+6Ws4b2VG026ZhsZgY4Vhgbg48T96rywi+7cTasWTICRburvz7r8UOf8EwU+TKtSBCPTziKhakBIRAeFExp2qcLajtFzl/2qhL1hfL20stF7Lc8IWERoTwnVLT6BgqTrqf04I71N+hEMfFZYtZ1YkbZJeKUi4fJsF1T5Vb6l6ta73ixk6hIhOWJfi4bNB4kS+6lnUVDvrK9E+jSu+iE5nlId9wHxOPlsslmDmTNJrwlY6CxeE6Oa2kOSImPxO25UJ6GPqWBxzn+uYde01uFNuYIK1ebbDwZftiaJlkMTsPsM+AKdPffF/Uo6MeCrBQa/rV7vdnimgKRGcK6OCRPNcb44gNPXeY/o7B9F9a5bZOiiytZDTQ5XJ0ohqeOc+VFtbZ7khj9qvfhVPX/a2JIYk2BiWXluXq2xlvEPNyxGrsT5yR78LYA9v8jiGRTl0kynPj/V/g4kFhLc3JPhs8TxVVgIXCM8H0KdVu2ijHBOUHrT6OwLiCfNHXlquuJVVLsj+e+8Hlbbq/44LvLa9L92QLufZWnBVtBtV9tV+wsi93JZQsxskqv2W5n064CcGA8k=
deploy:
  github_token:
    secure: rlTqGDJzSB87xGNM7M+NBe8EE2kMx9oXaVxk/A94CIsgV1cjJSKGBk40mmO48s6IFe60UQAGZoJVgmup65ggNcs5wq646Z9Hqik7VU5qtIzxP1PFaIdcfoiH1J20yB3UbPsqBirucXm2ZdLyPeVxhLdXEa0I2o9c5jpkXU6qsVsPgjKPPFqWPnhcnmJBHDusrUXejiZedfyxDUpPPVpriV1T7iJtoHgtjgNVQlLqvo7k6BvwjnqM8SjVsqS62X0q2N2NdTmjihxu0QyAKhUPKEYAkQmx0W5gtxJh0xmsD8yXsJDiaQ/pL83glW41YWzMmqNxXt/qMXJbnFMRy9mem3gtKsXRb6AfBmfoJc2aZYFHFiCBP+1eAYtP+DxAL+/TZtvvgEAYbkiMM9DkZgX1lfvlCkcJuCZri5Ovn8u/FQQnOS2VkOe34NjZJPWfI0Ya2qDTIYmj69f3V2CYGHddvPwPYjskuM6ZPpKWDZu7S/GAZtyKYn9d+1QpuIIrjMDUrJ1WtN2WbDlFUjVoeGMVE0406QBFnxU4Gmpx8gu3vVOFEllsTCrCwM6ymmPKWS3IZR5h0PuZKdI9bKztO5BpyBSjAmLlawNa+c+vvwhvCOE3XD2ot8EK2sMlmNjcqrDeZdrAtPMqL3SDaftR+aQm9fV2rAR0vcGnyJP3sUsgk/8=
