language: node_js
node_js: lts/*
cache:
  npm: false
before_script: 
script:
- yarn install
- yarn build
deploy:
  local_dir: ".vuepress/dist/"
  provider: pages
  skip_cleanup: true
  name: Travis Build Bot
  keep_history: true
  on:
        branch: master
      target_branch: gh-pages
  github_token:
    secure: atNwY1s8qOGac6zQm84k8m2ZHh0vgkV35PtjeeII4+feL9gINJ8opuC9ckJcgyUs+JrYV2msSVRIAiiEh6CQtlMLaOGAB/b3w/zxDXTHGVVe+FjKGM66DCxmvb7Y6SvDJkqSgYLksQfXZNSgSSwQEAYislBhxcXf8tEx8oKTLpbKzgNMoWpIoFXqYWU/DGxCYFmNTM6InBdu0V8J5cfgHZ7dy05AF0jHwFTMNLl/7lTX/xjwpfnnyBvljmt7MTR0n9pcLsvGRwmnKGfIMnxE0pyM6096sItU1WLsCq4WW0+a8zG/YMhj9GMVZ/q/8m6GfppQ2+Z2jdyq79tij+SdDnQXvWBdaGw3nfzk+MYiYIEHgit5sZlsS0+KfMk3CkOGsZFMMbrM6ezYiaKIbTbH+ztPfabwPrK/PbWbBP3ie5pYqF1piGbsU6LxjY4rtlvYCSmhP1y0VvhF5KEt6dwpCrCN5qt+x1VZn4ONHq5XGE0GsV85VzzMCjtMPKn0Xmj9Tzk0mplBKGlgrSCFgDfdRf36spt1phC9AZJAl2Vibay3c36wXIMlIeRWJd0GubrB2RgaWwB38CiXPzijucG6g6KGDstXj3gHlZMiJEXp86bjuE5/zO9ZX0FDOL3UsE7z+fGfaliORBxkd5QB9SxLVgTDb3rYrKRUpsbIS+Rb164=
dd:
  secure: w5wD73uky5frFGXQumYQya9EYGNrYwDn+l0NVeVDERVj7Hngkk3VnH9tiy7ooa89309JoaX09MgDrmmo9emb50ssS2mik0O8Zc2G1M7IP14NKZju1yCcFZZVvlvGARKd9xI78iEyrXefqXbrZQOqrltAACHfoAFWm3sAlT4ArQ0Uzwaxr9iR8yysi72HsW5tFfGmNfRLVCRwHgjgc9I6lLscVZ1lCiUILP15f9jMBQu7Tsiyx14QlU0EN4EgXveqV3UqsdltAk9LMttQ0OuzMf3388lJcLFsltVTT6nElyWC9NzgpBYhr/r3gKK85wjb9bpTAvL4rZesPomYicwH+j0z7s7FBpiMN8ofCPqT8WMUron9aJs3/xbPNdFS0IHNfw5ljdKpySK23OKm2z6ymIYLkjYels1RbRlfp1cjoDomZJzUD/Zoxqos0A0d2uPtYBz1ZWfyHmjQllpZheCa5KIIbY/bk8isJg2xT1rDOZ3mpaRP7GjvstB/t5BDt0Isaf2ToCfDZs4rBvCEIfn9VpDn5FvZAJ78csoxZtYTFk5/riJbsf50194KY2CaEmwH+FfI6cN56e+T33wj9olgJNQf55trw6G79ZDSTlVTk0EMa8yZN9vlb13yiO5wlIR2+1MPoJc+A6rn22Qje+j/UZfDYfAYBkXGiRR5f9b8dpg=
