language: node_js
node_js: node
cache:
  npm: true
jobs:
  include:
    - name: "Build and Push"
      script: 
      - npm run build
      deploy:
        local_dir: .vuepress/dist/
        provider: pages
        skip_cleanup: true
        name: Travis Build Bot
        keep_history: true
        on:
          branch: master
        target_branch: gh-pages
        # committer_from_gh: true
        # allow_empty_commit: true
        token:
          secure: atNwY1s8qOGac6zQm84k8m2ZHh0vgkV35PtjeeII4+feL9gINJ8opuC9ckJcgyUs+JrYV2msSVRIAiiEh6CQtlMLaOGAB/b3w/zxDXTHGVVe+FjKGM66DCxmvb7Y6SvDJkqSgYLksQfXZNSgSSwQEAYislBhxcXf8tEx8oKTLpbKzgNMoWpIoFXqYWU/DGxCYFmNTM6InBdu0V8J5cfgHZ7dy05AF0jHwFTMNLl/7lTX/xjwpfnnyBvljmt7MTR0n9pcLsvGRwmnKGfIMnxE0pyM6096sItU1WLsCq4WW0+a8zG/YMhj9GMVZ/q/8m6GfppQ2+Z2jdyq79tij+SdDnQXvWBdaGw3nfzk+MYiYIEHgit5sZlsS0+KfMk3CkOGsZFMMbrM6ezYiaKIbTbH+ztPfabwPrK/PbWbBP3ie5pYqF1piGbsU6LxjY4rtlvYCSmhP1y0VvhF5KEt6dwpCrCN5qt+x1VZn4ONHq5XGE0GsV85VzzMCjtMPKn0Xmj9Tzk0mplBKGlgrSCFgDfdRf36spt1phC9AZJAl2Vibay3c36wXIMlIeRWJd0GubrB2RgaWwB38CiXPzijucG6g6KGDstXj3gHlZMiJEXp86bjuE5/zO9ZX0FDOL3UsE7z+fGfaliORBxkd5QB9SxLVgTDb3rYrKRUpsbIS+Rb164=
