language: node_js
node_js: node
cache:
  npm: true
jobs:
  include:
  - name: Build and Push
    script:
    - npm run build
    deploy:
      local_dir: ".vuepress/dist/"
      provider: pages
      skip_cleanup: true
      name: Travis Build Bot
      keep_history: true
      on:
        branch: master
      target_branch: gh-pages
      token:
        secure: atNwY1s8qOGac6zQm84k8m2ZHh0vgkV35PtjeeII4+feL9gINJ8opuC9ckJcgyUs+JrYV2msSVRIAiiEh6CQtlMLaOGAB/b3w/zxDXTHGVVe+FjKGM66DCxmvb7Y6SvDJkqSgYLksQfXZNSgSSwQEAYislBhxcXf8tEx8oKTLpbKzgNMoWpIoFXqYWU/DGxCYFmNTM6InBdu0V8J5cfgHZ7dy05AF0jHwFTMNLl/7lTX/xjwpfnnyBvljmt7MTR0n9pcLsvGRwmnKGfIMnxE0pyM6096sItU1WLsCq4WW0+a8zG/YMhj9GMVZ/q/8m6GfppQ2+Z2jdyq79tij+SdDnQXvWBdaGw3nfzk+MYiYIEHgit5sZlsS0+KfMk3CkOGsZFMMbrM6ezYiaKIbTbH+ztPfabwPrK/PbWbBP3ie5pYqF1piGbsU6LxjY4rtlvYCSmhP1y0VvhF5KEt6dwpCrCN5qt+x1VZn4ONHq5XGE0GsV85VzzMCjtMPKn0Xmj9Tzk0mplBKGlgrSCFgDfdRf36spt1phC9AZJAl2Vibay3c36wXIMlIeRWJd0GubrB2RgaWwB38CiXPzijucG6g6KGDstXj3gHlZMiJEXp86bjuE5/zO9ZX0FDOL3UsE7z+fGfaliORBxkd5QB9SxLVgTDb3rYrKRUpsbIS+Rb164=
deploy:
  github_token:
    secure: tVxaufr6X1CXi66nR3f0xCgl5w1SwH1zOnnR0Qls/eHmSj3Fe6S7/ZqL6AXZqW+7BHHVXHcsis0/8/EcsiMBOS+lGAfM248P25XSEvjrTTj00Hmkl8iNQXAB3yOnB87TZP4athl5ZhUoQjBf3wxWiDZpk5ikrZAc2csipeXoddBoH/jWLxHMY5e0H5fdyFlXxInzHifIzoSjWWG2dF4bPy7UD9APCdEll9Qbdo9BLJVqt4mVR53ldA4tBlWdhH2NY1N6tHVrHTxgHp1rnDgHy9lYpvReJuDB012Smv1C+U21sBOniI6WIq7nlUFZDx0C9+W0mzhfkP624pNxNeJmVAwQv5Hj132qQdr/Yi3pvtfROorOF+37lg90zAtikj1Ludqk5eYbGcrGod7FkzhhkSdYXwRlqgUZZNNz5GY7pSUdVnwZP6OAWJO9LkKQrscaIzaB9/EBIHyWmNWKWS48fYM2z9x1PXv/nZPFJsQ4OkYxq+t92eMX3DXVD2hqwb45bhwtCim2djbGwUMDml7ycLBf7AORf9COPlWBGmrI6uOciT7Fbax99khQ06WpeEvZH7gk6q2GbJxP5FUVoIfmD0mdm7Qs1lWoWQ4V6soQ0A3LVR0UV2wNeT0DjjGpF7FPWDEKe0QQM6FHmM36QPf6MYRIRsgVjbfCzbZlREeRiMQ=
